# Generated by Django 3.0.2 on 2020-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=16)),
                ('purchases', models.IntegerField()),
                ('game_url', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
        ),
    ]
