# Generated by Django 3.0.2 on 2020-02-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_developer',
        ),
    ]
