# Generated by Django 3.0.2 on 2020-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
