# Generated by Django 3.0.2 on 2020-02-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20200208_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='purchases',
        ),
    ]
