# Generated by Django 2.2.7 on 2020-01-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20200129_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webshop.User'),
        ),
    ]
