# Generated by Django 2.2.7 on 2020-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20200118_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture_url',
            field=models.URLField(default='https://store-images.s-microsoft.com/image/apps.58949.14571142807322667.df9fc94b-3bd3-4ec2-b7a2-423331d84b17.5883e11e-8555-4114-83b7-72d1cb12cd6e?mode=scale&q=90&h=1080&w=1920'),
        ),
    ]
