# Generated by Django 3.0.2 on 2020-02-08 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop', '0004_remove_game_purchases'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('game', 'buyer', 'pid')},
        ),
    ]
