# Generated by Django 2.2.7 on 2020-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20200116_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
