# Generated by Django 2.2.7 on 2020-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20200129_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=1000),
        ),
    ]
