# Generated by Django 3.0.2 on 2020-01-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20200129_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameInfo', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buy_completed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buy_started',
        ),
        migrations.AddField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture_url',
            field=models.URLField(blank=True, default='https://store-images.s-microsoft.com/image/apps.58949.14571142807322667.df9fc94b-3bd3-4ec2-b7a2-423331d84b17.5883e11e-8555-4114-83b7-72d1cb12cd6e?mode=scale&q=90&h=1080&w=1920'),
        ),
        migrations.DeleteModel(
            name='GameStatus',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop.Game'),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop.UserProfile'),
        ),
    ]
