# Generated by Django 3.0.2 on 2020-01-30 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0007_auto_20200130_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buy_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
