# Generated by Django 3.0.2 on 2020-01-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20200130_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.UserProfile'),
        ),
    ]
