# Generated by Django 3.0.2 on 2020-01-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20200129_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop.Game'),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop.User'),
        ),
        migrations.AlterUniqueTogether(
            name='gamedata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='gameID',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='username',
        ),
    ]
