# Generated by Django 3.0.2 on 2020-02-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20200130_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('buyer', 'game')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='checksum',
        ),
    ]
