# Generated by Django 3.0.2 on 2020-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0009_auto_20200131_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='user',
            field=models.TextField(),
        ),
    ]
