# Generated by Django 3.0.2 on 2020-02-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0010_auto_20200207_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
